name: pypy3
version: '7.2.0'
summary: PyPy is a fast, compliant alternative implementation of the Python language
description: |
  PyPy is a replacement for CPython. It is built using the RPython language
  that was co-developed with it. The main reason to use it instead of CPython
  is speed; it runs generally faster.
license: MIT

grade: stable
confinement: classic

apps:
  pypy3:
    command: bin/pypy3

base: core
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: ppc64el
  - build-on: s390x

parts:
  pypy3:
    plugin: dump
    source:
      - on amd64: https://bitbucket.org/pypy/pypy/downloads/pypy3.6-v$SNAPCRAFT_PROJECT_VERSION-linux64.tar.bz2
      - on arm64: https://bitbucket.org/pypy/pypy/downloads/pypy3.6-v$SNAPCRAFT_PROJECT_VERSION-aarch64.tar.bz2
      - on ppc64el: https://bitbucket.org/pypy/pypy/downloads/pypy3.6-v$SNAPCRAFT_PROJECT_VERSION-ppc64le.tar.bz2
      - on s390x: https://bitbucket.org/pypy/pypy/downloads/pypy3.6-v$SNAPCRAFT_PROJECT_VERSION-s390x.tar.bz2
    override-build: |
      bin/pypy3 -m compileall -qx '/tests?[_/]' .
      patch -p1 < $SNAPCRAFT_PROJECT_DIR/tcl-path.patch
      patch -p1 < $SNAPCRAFT_PROJECT_DIR/curses-path.patch
      snapcraftctl build
    build-packages:
      - tcl-dev
      - tk-dev
    stage-packages:
      - libfontconfig1
      - libtcl8.6
      - libtk8.6
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxft2
      - libxrender1
      - libxss1
      - ncurses-base
